name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '!test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install --only=prod

      - name: Build Docker image
        run: |
          echo "DEPLOYED_FROM=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          docker build -t nodeapp .
          docker tag nodeapp parsuboy666/digimailerregistry:n1.0

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push parsuboy666/digimailerregistry:n1.0
