name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '!test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install --only=prod

      - name: Build Docker image
        run: |
          echo "DEPLOYED_FROM=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          docker build -t nodeapp:latest .
          docker tag nodeapp:latest parsuboy666/digimailerregistry:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push parsuboy666/digimailerregistry:latest


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
        run: |
          echo "DEPLOYED_To_Container"
          docker run -p 8088:3000 -d parsuboy666/digimailerregistry:latest
